### PR TITLE
community guidelines

### PR DESCRIPTION
**Pull request by franziskuskiefer**
This PR adds some community guidelines and templates for issues and PRs for #4 .
I'll do another pass when the repository is public because some of this only works for public repositories.

### CODE REVIEW

**Review by karthikbhargavan — COMMENTED** [review]
Does CONTRIBUTING.md constitute a CLA?
Should we add some boilerplate text at the bottom of README.md?

**Comment by franziskuskiefer** [comment]
> Does CONTRIBUTING.md constitute a CLA? Should we add some boilerplate text at the bottom of README.md?

Good point. I added a CLA.md and mention it in CONTRIBUTING.md.
The PR template also requests to tick the box for heaving read the agreements.
Do you think that's enough?

**Comment by franziskuskiefer** [comment]
@karthikbhargavan ?

**Comment by karthikbhargavan** [comment]
Looks good to me.

**Review by karthikbhargavan — APPROVED** [review]

**Pull request merged**
