### PR TITLE
Add Nix files and commit `Cargo.lock`

### PR DESCRIPTION
**Pull request by pnmadelaine**

### CODE REVIEW

**Review by W95Psp — COMMENTED** [review]
Thanks!
I have a few comments:
 - Why only "x86_64-linux"? Things should work fine on other architectures.
 - We should expose the Rust binaries provided by the crate (e.g. simple_https_{server,client}) 
 - We should also run `hax-driver.py extract-proverif`

**Review by franziskuskiefer — DISMISSED** [review]
When committing the log file you need to update the CI here to update dependencies.

**Comment by franziskuskiefer** [comment]
I don't see anything weird

**Comment by pnmadelaine** [comment]
> I don't see anything weird.

Having the lockfile completely ignored by CI, and thus the CI not giving information about the current build status of the repository is at the very least counter-intuitive.

> In any case. This PR needs to go along with a CI here that tests the library without the lock file. I don't see how dependabot helps with that. But if you have a workflow with that, feel free to propose it.

The workflow we propose is to run tests with the locked dependencies, so as to ensure the same set of dependencies is used by developers, users and the CI, and to update them periodically with a separate workflow (dependabot, which is already configured on this repository).

**Comment by pnmadelaine** [comment]
> I don't see how dependabot helps with that.

dependabot will automatically open PRs to update outdated dependencies

**Review by W95Psp — APPROVED** [review]
Thanks, LGTM!

Looks like there is a linting issue, somehow :eyes: 
Can you rebase your PR with #119? I pushed a fix there

**Comment by pnmadelaine** [comment]
@W95Psp done!

**Comment by pnmadelaine** [comment]
I was just thinking, we should discuss committing `flake.lock`.
If it is committed it needs to be updated regularly, otherwise the nix build will quickly fail and the lock file will become useless anyway.
@W95Psp what do you think?

**Comment by W95Psp** [comment]
I see no point in not commiting flake.lock, of we don't commit flake.lock, we should drop the nix expressions all together.
The nix job you added will check the nix expressions are up to date as code changes, that's all we need imo.
Locked flakes are especially useful to make sure we'll be able to build the project in the future.

**Review by franziskuskiefer — APPROVED** [review]

**Review by karthikbhargavan — APPROVED** [review]

**Pull request merged**
