### PR TITLE
Allow X25519Kyber768Draft00 as KEM option

### LINKED ISSUE #122: Implement PQ hybrid handshake

### PR DESCRIPTION
**Pull request by jschneider-bensch**
This PR makes the hybrid post-quantum KEM [X25519Kyber768](https://www.ietf.org/archive/id/draft-tls-westerbaan-xyber768d00-03.html) available as a KEM option.

Fixes #122.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation
- [ ] Automation

### CODE REVIEW

**Comment by jschneider-bensch** [comment]
Still waiting for `libcrux-(ml-)kem` pre-release before I can mark this ready.

**Comment by franziskuskiefer** [comment]
@jschneider-bensch can you update this to pick up the ml-kem release?

**Comment by jschneider-bensch** [comment]
The dependency is actually on libcrux-kem, which provides the hybrid KEMs.

**Comment by franziskuskiefer** [comment]
https://crates.io/crates/libcrux-kem

**Review by franziskuskiefer — APPROVED** [review]
🚀

**Pull request merged**
